# Generated by Django 2.2 on 2023-07-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('numeroOrden', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('mesa', models.IntegerField()),
                ('mesero', models.IntegerField()),
                ('codigoEstado', models.IntegerField()),
                ('productos', models.CharField(max_length=100)),
                ('notas', models.TextField(max_length=100)),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'orden',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('numeroProducto', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
